# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    target-branch: "dev"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: /owmods_gui/frontend
    target-branch: "dev"
    schedule:
      interval: "weekly"
