[package]
name = "owmods_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
owmods_core = { path = "../../owmods_core" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2.4", features = ["app-all", "dialog-confirm", "dialog-message", "dialog-open", "dialog-save", "os-all", "shell-open", "window-close", "window-set-title"] }
anyhow = "1.0.69"
tokio = { version = "1.25.0", features = ["sync", "macros"] }
log = { version = "0.4.17", features = ["std", "serde"] }
rust-fuzzy-search = "0.1.1"
typeshare = "1.0.0"
tempdir = "0.3.7"
regex = "1.7.1"
chrono = "0.4.23"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
