[package]
name = "owmods_gui"
version = "0.7.2"
license = "GPL-3.0-or-later"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.3.0", features = [] }

[dependencies]
owmods_core = { version = "0.7.2", path = "../../owmods_core" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.3.0", features = ["app-all", "dialog-ask", "dialog-confirm", "dialog-message", "dialog-open", "dialog-save", "os-all", "shell-open", "updater", "window-set-focus", "window-set-title"] }
anyhow = "1.0.69"
tokio = { version = "1.25.0", features = ["sync", "macros"] }
log = { version = "0.4.17", features = ["std", "serde"] }
typeshare = "1.0.0"
notify = { version = "6.0.1", default-features = false, features = ["macos_kqueue"] }
regex = "1.7.1"
time = { version = "0.3.15", features = ["macros"] }
tauri-plugin-deep-link = "0.1.0"
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }
opener = "0.6.1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
