[package]
name = "owmods_core"
authors = ["Bwc9876 <bwc9876@gmail.com>"]
description = "The core library for the Outer Wilds Mod Manager"
version = "0.1.0"
edition = "2021"
readme = "./README.md"
repository = "https://github.com/Bwc9876/ow-mod-man/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
opener = "0.5.0"
directories = "4.0.1"
reqwest = { version = "0.11.14", features = ["blocking", "json"] }
glob = "0.3.1"
version-compare = "0.1.1"
anyhow = "1.0.68"
zip = { version = "0.6.3", default-features = false, features = ["deflate", "zstd"] }
tempdir = "0.3.7"
futures = "0.3.26"
log = "0.4.17"
tokio = { version = "1.25.0", features = ["net", "time", "process"] }
serde_repr = "0.1.10"
uuid = { version = "1.3.0", features = ["v4", "fast-rng"] }
typeshare = "1.0.0"
tokio-test = "0.4.2"
