name: Continuous Integration

on:
  push:
    paths-ignore:
      - .github/workflows/release.yml
      - "**/README.md"
      - "**/CONTRIBUTING.md"
      - "LICENSE"
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  rs:
    name: Check Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev
          
      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Check Formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            ./owmods_core -> target
            ./owmods_cli -> target
            ./owmods_gui/backend -> target

      - name: Make Stub Dist Dir
        run: mkdir owmods_gui/dist

      - name: Check Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings

      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
  js:
    name: Check Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./owmods_gui/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint-dry

      - name: Check Formatting
        run: pnpm prettier-check
