name: Format (Renovate Only)

on:
  pull_request:
    branches: [renovate/js]
  push:
    branches: [renovate/js]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          same_commit: True
          only_changed: True
