name: Post Core Release

on:
  push:
    tags:
      - "core_v*"

jobs:
  crates:
    name: Publish To Crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}-rust-cache-${{ hashFiles('Cargo.lock') }}

      - name: Publish Core
        uses: actions-rs/cargo@v1
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          command: publish
          args: -p owmods_core
